### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by alex-tee** [wolf-plugins/wolf-spectrum#55]
There are no license headers and no mention of the license. I see the unedited GPL3 license but is the code GPL3 only or GPL3 or later?

**Comment by pdesaulniers** [comment]
Indeed, this should be made clearer. The code is licensed under GPLv3 or later: https://github.com/wolf-plugins/wolf-spectrum/blob/0328d156f422035fe9309b1b19a4f26fe0ab4d71/src/WolfSpectrumPlugin.cpp#L63-L66

**Comment by pdesaulniers** [comment]
I added the licensing information in a few places: https://github.com/wolf-plugins/wolf-spectrum/commit/28e50b141439b7c64b570afebce04998d26016ee

**Comment by alex-tee** [comment]
Thanks! Ideally every source file should have a license header but this is better than nothing. I copied most of the code in https://github.com/wolf-plugins/wolf-spectrum/blob/a8f92624b952a0ad34ade1025180ed5be280eaa4/src/Widgets/src/Spectrogram.cpp for a spectrum analyzer

**Comment by pdesaulniers** [comment]
> Thanks! Ideally every source file should have a license header but this is better than nothing.

Yes, sorry, every source file should have a valid SPDX license identifier now :)

> I copied most of the code in https://github.com/wolf-plugins/wolf-spectrum/blob/a8f92624b952a0ad34ade1025180ed5be280eaa4/src/Widgets/src/Spectrogram.cpp for a spectrum analyzer 

That's great! I'm glad the code is being useful :grin:

**Comment by pdesaulniers** [comment]
The project should now be [REUSE-compliant](https://reuse.software/). I think this issue can be closed! Let me know if something still isn't clear with regards to the licensing.

**Comment by alex-tee** [comment]
Perfect, thanks!
