### ISSUE TITLE
How to select audio source?

### ISSUE THREAD

**Issue by xaionaro** [wolf-plugins/wolf-spectrum#56]
Hello.

I've launched `wolf-spectrum` on Linux, but it keeps showing no audio:
![Screenshot from 2024-06-02 18-36-08](https://github.com/wolf-plugins/wolf-spectrum/assets/2349376/b007120d-8ae7-4f2b-b39d-b49e54f8a15c)

How to select the audio source?

**Comment by pdesaulniers** [comment]
Hello!

The standalone build of Wolf Spectrum is implemented as a JACK Application.

You can connect the audio source to Wolf Spectrum by using a JACK GUI such as [QJackCtl](https://qjackctl.sourceforge.io/), or [qpwgraph](https://gitlab.freedesktop.org/rncbc/qpwgraph) (if your system uses PipeWire for audio)

It is not currently possible to select the audio source through the GUI.

**Comment by xaionaro** [comment]
In my case I can control it only from CLI and it should setup automatically. But I see, thanks.

**Comment by xaionaro** [comment]
Just in case: confirmed that the audio source is connectable via qpwgraph, so assuming should also be connectible using pw-link. Will check later.

**Comment by pdesaulniers** [comment]
I added an 'How to use" section in the README!

**Comment by cyanescent** [comment]
Great visualization tool, thank you!
